### ISSUE TITLE
Two different fiskaly cloud TSE's assigned to Cashbox and to Queue

### ISSUE THREAD

**Issue by Solrosy** [fiskaltrust/faq#113]
Hi guys,

I did some testing and assigned a different TSE to the cashbox than to the queue.
It didn't give me any error message and I got signed receipts back.

Is this on purpose?
Why can this be done? Which TSE is chosen?

**Comment by TSchmiedlechner** [comment]
Hi @Solrosy,
good question! It works like this:
- The Queue uses the first URL of the SCU/TSE that is linked to the Queue
- The Cashbox contains only those items assigned to it (i.e. in your scenario, the SCU that is linked to the Queue is not deployed and not started when you run the Launcher - it will only contain the SCU you selected for the Cashbox)

I assume that your scenario works because the SCUs have the same URLs? If that's the case, please keep in mind that while this is technically possible, it's of course not a recommended architecture and should not be applied in production scenarios. 😄 

Kind regards, Tom

**Comment by Solrosy** [comment]
Thanks Tom.
