### ISSUE TITLE
add further meta-tags

### ISSUE THREAD

**Issue by magdignomad** [fiskaltrust/faq#53]
Add tags for publishing the FAQ and respect it on all channels

Publication
- publish-all (will be published public on all channels)
- publish-website (publish it on the website of the tagged market)
- publish-portal (publish it on the portal of the tagged market)
- publish-docs (publish it on the docs-website)
- publish-public (visible for everyone)
- publish-fiskaltrust (only visible for employees of fiskaltrust, overrides publish on website)
- publish-none (won't be published on any channel)

Extend tags
- portal-all (for production and sandbox)
- portal-sandbox (concerns only sandbox)
- portal-production (concerns only production)

**Comment by christian-rogobete** [comment]
as discussed, I added the tags

portal-sandbox (concerns only sandbox)
portal-production (concerns only production)

I did not add "portal-all" but extended "portal" with the comment "(for production and sandbox)" so that we don't need to change existing q&a.

Pls. see PR: https://github.com/fiskaltrust/faq/pull/61

**Comment by magdignomad** [comment]
I commented it in the PR. please follow there the thread
